---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zilla-petstore
  namespace: petstore
  labels:
    app.kubernetes.io/name: zilla-petstore
    app.kubernetes.io/instance: zilla
    app.kubernetes.io/managed-by: Helm
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/cors-allow-headers: '*'
    nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  tls:
    - hosts:
        - petstore.aklivity.io
      secretName: petstore-prod-tls
  ingressClassName: nginx
  rules:
    - host: petstore.aklivity.io
      http:
        paths:
          - backend:
              service:
                name: zilla
                port:
                  number: 7114
            pathType: Prefix
            path: /
